<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net6.0;net8.0</TargetFrameworks>
    <VersionPrefix>0.2.0</VersionPrefix>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/jakegough/jaytwo.subprocess.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>    
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="jaytwo.RuntimeRevelation" Version="0.2.1-*" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.*" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="jaytwo.Subprocess.UnitTests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" Link="README.md" />
  </ItemGroup>

</Project>
